# Generated by Django 5.2 on 2025-04-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('gst_number', models.CharField(max_length=50)),
                ('pan_number', models.CharField(max_length=20)),
                ('sac_number', models.CharField(max_length=20)),
                ('bank_account', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Transport Company',
                'verbose_name_plural': 'Transport Companies',
            },
        ),
    ]
